version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.2
jobs:
  builds_builds:
    docker:
      - image: golang:1.11
    steps:
      - checkout
      - run:
          working_directory: builds.clementine-player.org
          command: go build

  deploy_builds:
    executor: gcp-cli/google
    steps:
      - gcp-cli/initialize
      - checkout
      - run:
          name: Deploy builds.clementine-player.org Function
          working_directory: builds.clementine-player.org
          command: >
            gcloud functions deploy
            Serve
            --runtime go111
            --trigger-http
            --project clementine-data
            --region us-central1

  firebase_deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Install Firebase CLI
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Firebase deploy
          command: ./firebase-deploy/node_modules/.bin/firebase deploy

  build_www:
    docker:
      - image: alpine:3.11
    steps:
      - run:
          name: Install dependencies
          command: apk --no-cache --no-progress add py-django make openjdk8-jre-base gettext
      - checkout
      - run:
          name: Build CSS and languages
          command: make
          working_directory: www.clementine-player.org
      - persist_to_workspace:
          root: www.clementine-player.org
          paths:
            - '*'

  deploy_www:
    executor: gcp-cli/google
    steps:
      - gcp-cli/initialize
      - attach_workspace:
          at: www.clementine-player.org
      - run:
          name: Add environment to app.yaml
          command: >
            echo 'env_variables:' >> app.yaml &&
            echo "GITHUB_TOKEN: ${GITHUB_TOKEN}" >> app.yaml
          working_directory: www.clementine-player.org
      - run:
          name: Debug
          command: cat app.yaml
          working_directory: www.clementine-player.org
      - run:
          name: Deploy WWW
          command: gcloud app deploy --project ${GOOGLE_PROJECT_ID} app.yaml cron.yaml
          working_directory: www.clementine-player.org

workflows:
  version: 2
  all:
    jobs:
      - builds_builds
      - deploy_builds:
          context: gcp
          requires:
            - builds_builds
          filters:
            branches:
              only: master
      - firebase_deploy:
          context: gcp
          filters:
            branches:
              only: master
      - build_www
      - deploy_www:
          context: gcp-www
          requires:
              - build_www
          filters:
            branches:
              only: master
