application: clementine-data
version: dev
runtime: python27
threadsafe: yes
api_version: 1

libraries:
- name: webapp2
  version: 2.5.1
- name: jinja2
  version: "2.6"

builtins:
- remote_api: on
- appstats: on

inbound_services:
- xmpp_message
- channel_presence

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /_tasks/.*
  script: tasks.app
  login: admin

- url: /projects.*
  script: projects.app

- url: /versions
  script: clementine.app
  login: admin

- url: /sparkle
  script: clementine.app

- url: /sparkle-windows
  script: clementine.app

- url: /rainymood
  script: clementine.app

- url: /icecast-directory
  script: clementine.app

- url: /
  script: projects.app

- url: /c2dm/.*
  script: c2dm.app
  secure: always
  login: required

- url: /skydrive
  script: skydrive.app

- url: /channel.*
  script: channel.app
  secure: always

- url: /_ah/channel/.*
  script: channel.app
  secure: always

- url: /.*
  script: clementine.app
