application: clementine-data
version: dev
runtime: python27
threadsafe: yes
api_version: 1

builtins:
- remote_api: on

inbound_services:
- xmpp_message

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /_tasks/.*
  script: tasks.app
  login: admin

- url: /projects.*
  script: projects.app

- url: /versions
  script: clementine.app
  login: admin

- url: /sparkle
  script: clementine.app

- url: /sparkle-windows
  script: clementine.app

- url: /rainymood
  script: clementine.app

- url: /icecast-directory
  script: clementine.app

- url: /
  script: projects.app

- url: /c2dm/.*
  script: c2dm.app
  secure: always
  login: required

- url: /.*
  script: clementine.app

libraries:
- name: webapp2
  version: 2.0.2
