runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: "2.6"


handlers:
- url: /css
  static_dir: static/css
  expiration: "1d"
  secure: always

- url: /images
  static_dir: static/images
  expiration: "7d"
  secure: always

- url: /fonts
  static_dir: static/fonts
  expiration: "7d"
  secure: always

- url: /screenshots
  static_dir: static/screenshots
  expiration: "7d"
  secure: always

- url: /js
  static_dir: static/js
  secure: always

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  expiration: "7d"
  secure: always

- url: /thumbnails/.*
  script: thumbnailer.app
  secure: always

- url: /.*
  script: main.app
  secure: always

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?\.jar
