on:
  push:
    branches:
      - master
    paths:
      - 'lambda.clementine-player.org/bio/**'
      - '.github/workflows/bio.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        uses: docker/build-push-action@v2.2.1
        with:
          context: lambda.clementine-player.org/bio
          file: lambda.clementine-player.org/bio/Dockerfile
          push: false
          tags: |
            gcr.io/clementine-web/bio

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: clementine-web
          workload_identity_provider: projects/460637942860/locations/global/workloadIdentityPools/github-actions/providers/website-repo
          service_account: github-deploy@clementine-web.iam.gserviceaccount.com
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Install beta gcloud components
        run: gcloud components install beta

      - name: Configure docker auth
        run: gcloud auth configure-docker

      - name: docker push
        run: docker push gcr.io/clementine-web/bio

      - name: Deploy service to Cloud Run
        run: >
          gcloud beta run deploy bio
          --region europe-north1
          --image gcr.io/clementine-web/bio
          --platform managed
          --allow-unauthenticated
          --project clementine-web
          --set-secrets KG_API_KEY=KG_API_KEY:latest
          --service-account bio-511@clementine-web.iam.gserviceaccount.com
          --max-instances=1
          --memory=128Mi
