on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: clementine-data
          workload_identity_provider: projects/611551928920/locations/global/workloadIdentityPools/github-actions/providers/website-repo
          service_account: github-deploy@clementine-data.iam.gserviceaccount.com
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Deploy data.clementine-player.org
        working-directory: data.clementine-player.org
        run: gcloud app deploy app.yaml
