on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: alpine:3.14
    steps:
      - name: Install dependencies
        run: apk --no-cache add py-django make openjdk8-jre-base gettext
      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: "clementine-web"
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        working-directory: www.clementine-player.org
        run: make
      - name: Add environment to app.yaml
        working-directory: www.clementine-player.org
        run: >
          echo 'env_variables:' >> app.yaml &&
          echo "  GITHUB_TOKEN: ${WWW_GITHUB_TOKEN}" >> app.yaml
      - name: Deploy WWW
        working-directory: www.clementine-player.org
        run: gcloud app deploy app.yaml
